// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Roborally.infrastructure.persistence;

#nullable disable

namespace Roborally.infrastructure.persistence.Migrations
{
    [DbContext(typeof(AppDatabaseContext))]
    [Migration("20250919085704_updateUserTable")]
    partial class updateUserTable
    {
        /// <inheritdoc />
/// <author name="Sachin Baral 2025-09-19 13:01:07 +0200 19" />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameLobbyUsers", b =>
                {
                    b.Property<Guid>("GameLobbyGameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("GameLobbyGameId", "Username");

                    b.HasIndex("Username");

                    b.ToTable("GameLobbyUsers");
                });

            modelBuilder.Entity("Roborally.core.domain.Lobby.GameLobby", b =>
                {
                    b.Property<Guid>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameRoomName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HostUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GameId");

                    b.ToTable("GameLobby", (string)null);
                });

            modelBuilder.Entity("Roborally.core.domain.User.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<Guid?>("GameLobbyGameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Username");

                    b.HasIndex("GameLobbyGameId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GameLobbyUsers", b =>
                {
                    b.HasOne("Roborally.core.domain.Lobby.GameLobby", null)
                        .WithMany()
                        .HasForeignKey("GameLobbyGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Roborally.core.domain.User.User", null)
                        .WithMany()
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Roborally.core.domain.User.User", b =>
                {
                    b.HasOne("Roborally.core.domain.Lobby.GameLobby", null)
                        .WithMany("JoinedUsers")
                        .HasForeignKey("GameLobbyGameId");
                });

            modelBuilder.Entity("Roborally.core.domain.Lobby.GameLobby", b =>
                {
                    b.Navigation("JoinedUsers");
                });
#pragma warning restore 612, 618
        }
    }
}