// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Roborally.infrastructure.persistence;

#nullable disable

namespace Roborally.infrastructure.persistence.Migrations
{
    [DbContext(typeof(AppDatabaseContext))]
    [Migration("20250920101645_ChangeToLobbyname2")]
    partial class ChangeToLobbyname2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameLobbyJoinedUsers", b =>
                {
                    b.Property<Guid>("GameLobbyGameId")
                        .HasColumnType("uuid");

                    b.Property<string>("JoinedUsersUsername")
                        .HasColumnType("text");

                    b.HasKey("GameLobbyGameId", "JoinedUsersUsername");

                    b.HasIndex("JoinedUsersUsername");

                    b.ToTable("GameLobbyJoinedUsers");
                });

            modelBuilder.Entity("Roborally.core.domain.Lobby.GameLobby", b =>
                {
                    b.Property<Guid>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HostUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("LobbyName");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GameId");

                    b.HasIndex("HostUsername");

                    b.ToTable("GameLobby", (string)null);
                });

            modelBuilder.Entity("Roborally.core.domain.User.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GameLobbyJoinedUsers", b =>
                {
                    b.HasOne("Roborally.core.domain.Lobby.GameLobby", null)
                        .WithMany()
                        .HasForeignKey("GameLobbyGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Roborally.core.domain.User.User", null)
                        .WithMany()
                        .HasForeignKey("JoinedUsersUsername")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Roborally.core.domain.Lobby.GameLobby", b =>
                {
                    b.HasOne("Roborally.core.domain.User.User", null)
                        .WithMany()
                        .HasForeignKey("HostUsername")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
